name: vmbackup
base: core18
adopt-info: build
icon: logo.png
summary: vmbackup creates VictoriaMetrics data backups from instant snapshots
description: |
  `vmbackup`` supports incremental and full backups. Incremental backups are created automatically if the destination path already contains data from the previous backup. Full backups can be sped up with `-origin` pointing to an already existing backup on the same remote storage. In this case `vmbackup` makes server-side copy for the shared data between the existing backup and new backup. It saves time and costs on data transfer.

  Backup process can be interrupted at any time. It is automatically resumed from the interruption point when restarting `vmbackup` with the same args.

  Backed up data can be restored with https://docs.victoriametrics.com/vmrestore.html.

  **vmbackup supports the following `-dst` storage types:**
      *  GCS. Example: `gs://<bucket>/<path/to/backup>`
      *  S3. Example: `s3://<bucket>/<path/to/backup>`
      *  Azure Blob Storage. Example: `azblob://<container>/<path/to/backup>`
      *  Any S3-compatible storage such as MinIO, Ceph or Swift. See https://docs.victoriametrics.com/vmbackup.html#advanced-usage for details.
      *  Local filesystem. Example: `fs://</absolute/path/to/backup>`. Note that `vmbackup` prevents from storing the backup into the directory pointed by `-storageDataPath` command-line flag, since this directory should be managed solely by VictoriaMetrics or `vmstorage`.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  build:
    plugin: go
    go-channel: 1.22/stable
    go-importpath: github.com/VictoriaMetrics/VictoriaMetrics
    source: .
    source-type: local
    build-packages: [build-essential, make]
    override-build: |
      make app-local APP_NAME=vmbackup
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -p $SNAPCRAFT_PART_BUILD/bin/vmbackup $SNAPCRAFT_PART_INSTALL/bin/
      cp -p $SNAPCRAFT_PART_SRC/snap/local/vmbackup-wrapper $SNAPCRAFT_PART_INSTALL/bin/
    override-pull: |
      snapcraftctl set-version "$PKG_TAG"
      snapcraftctl pull
apps:
  vmbackup:
    command: bin/vmbackup-wrapper
    daemon: simple
    restart-condition: always
    restart-delay: 10s
    plugs: [network,network-bind]

plugs:
  network:
  network-bind:

layout:
  /var/lib/victoriametrics:
    bind: $SNAP_DATA/var/lib/vmbackup

architectures:
  - build-on: ['amd64']
    run-on: ['amd64']