name: vmrestore
base: core18
adopt-info: build
icon: logo.png
summary: vmrestore restores data from backups created by vmbackup
description: |
  VictoriaMetrics must be stopped during the restore process.

  Run the following command to restore backup from the given -src into the given -storageDataPath:

  `./vmrestore -src=<storageType>://<path/to/backup> -storageDataPath=<local/path/to/restore>`

      * `<storageType>://<path/to/backup>` is the path to backup made with vmbackup. vmrestore can restore backups from the following storage types:
          *  GCS. Example: -src=gs://<bucket>/<path/to/backup>
          *  S3. Example: -src=s3://<bucket>/<path/to/backup>
          *  Azure Blob Storage. Example: -src=azblob://<container>/<path/to/backup>
          *  Any S3-compatible storage such as MinIO, Ceph or Swift. See these docs for details.
          *  Local filesystem. Example: -src=fs://</absolute/path/to/backup>. Note that vmbackup prevents from storing the backup into the directory pointed by `-storageDataPath` command-line flag, since this directory should be managed solely by VictoriaMetrics or `vmstorage`.
      * `<local/path/to/restore>` is the path to folder where data will be restored. This folder must be passed to VictoriaMetrics in `-storageDataPath` command-line flag after the restore process is complete.

  The original `-storageDataPath` directory may contain old files. They will be substituted by the files from backup, i.e. the end result would be similar to https://askubuntu.com/questions/476041/how-do-i-make-rsync-delete-files-that-have-been-deleted-from-the-source-folder.


grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  build:
    plugin: go
    go-channel: 1.22/stable
    go-importpath: github.com/VictoriaMetrics/VictoriaMetrics
    source: .
    source-type: local
    build-packages: [build-essential, make]
    override-build: |
      make app-local APP_NAME=vmrestore
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -p $SNAPCRAFT_PART_BUILD/bin/vmrestore $SNAPCRAFT_PART_INSTALL/bin/
      cp -p $SNAPCRAFT_PART_SRC/snap/local/vmrestore-wrapper $SNAPCRAFT_PART_INSTALL/bin/
    override-pull: |
      snapcraftctl set-version "$PKG_TAG"
      snapcraftctl pull
apps:
  vmrestore:
    command: bin/vmrestore-wrapper
    daemon: simple
    restart-condition: always
    restart-delay: 10s
    plugs: [network,network-bind]

plugs:
  network:
  network-bind:

architectures:
  - build-on: ['amd64']
    run-on: ['amd64']